<?php

  // ==============================================

  // Products:

  $products = array( [
    "Vaporfly 2",
    "Men's Road Racing Shoes",
    "Continue the next evolution of speed with racing shoes designed to help you chase new goals and records. The Nike Vaporfly 2 builds on a model loved by racers everywhere with a redesigned upper that aims to improve comfort and breathability. From a 10K to a marathon, this version maintains the responsive cushioning and secure support of the original to help push you toward your personal best.",
    "shoes",
    "men",
     26000,
     26000,
  ],
 [
    "Dri-FIT Slam",
    "Women's Tennis Tank",
    "Crafted with our most innovative materials, this fitted tank pairs lightweight knit coverage with the breathability of mesh. The result is a statement-making top that will keep you cool and comfortable so you can play your best.",
    "clothes",
    "women",
     4697,
     6200,
  ],
 [
    "Infinity React 3",
    "Women's Road Running Shoes",
    "Celebrate every mile with these festive road runners. With soft and supportive cushioning, the Nike Infinity React 3 is built to help keep you on the run. A wider forefoot and higher foam stacks help shield you from recurring attrition so you can make running a daily habit. The springy responsiveness surprises you too, adding an element of pure speed to 1 of our most tested shoes. Plus, colorful confetti-inspired graphic accents add fresh energy to your run.",
    "shoes",
    "women",
     16500,
     16500,
  ],
 [
    "Dri-FIT One",
    "Women's Mid-Rise Printed Shorts",
    "These shorts are the ones that are down for everything you do—from long walks to HIIT to running errands. Their silky-smooth, ultrasoft woven fabric is balanced with sweat-wicking tech so you have ultimate comfort while feeling dry as you work out. The snug inner layer helps prevent chaffing so you can push yourself with uncompromising coverage.",
    "clothes",
    "women",
     5200,
     5200,
  ],
 [
    "Air Zoom Rival Fly 3",
    "Men's Road Racing Shoes",
    "Are you ready to ramp up the speed and go the distance? Built for training and racing, the Nike Air Zoom Rival Fly 3 features soft foam and durable abrasion-resistant rubber to help you conquer even the rockiest of roads. Plus, Nike Zoom Air provides a snappy feel as you push toward the finish line.",
    "shoes",
    "men",
     10000,
     10000,
  ],
 [
    "Sportswear Phoenix Fleece",
    "Women's High-Waisted Wide-Leg Sweatpants",
    "Rise up and transform your fleece wardrobe with strong cozy vibes. The extra-long, wide leg and hem vents of these Phoenix Fleece pants let you show off your favorite shoes while taller ribbing at the waist and an exaggerated drawcord ensure your look is anything but basic.",
    "clothes",
    "women",
     7000,
     7000,
  ],
 [
    "Invincible 2",
    "Men's Road Running Shoes",
    "The Nike Invincible 2 has the same supersoft feel that lets you feel the potential when your foot hits the pavement. We created the shoe with plenty of snappy responsiveness and incredible support to help keep you feeling secure and competitive. It's 1 of our most tested shoes, still designed for you to stay on the track and away from the sidelines.",
    "shoes",
    "men",
     10497,
     18000,
  ],
 [
    "Zegama",
    "Men's Trail Running Shoes",
    "Navigate the up and downs of uncompromising terrain with the Nike Zegama. Developed with great grip and stability, it has you covered so you can keep climbing and reach greater personal heights when the going gets grimy and gritty. Whether it's a challenging, rocky landscape going uphill or a steep, slick decline down a treacherous trail, feel confident when you decide to off-road it.",
    "shoes",
    "men",
     16000,
     11197,
  ],
 [
    "Pegasus 39",
    "Men's Road Running Shoes",
    "Let the Nike Pegasus 39 help you ascend to new heights. More lightweight up top than the Pegasus 38 and ideal to wear in any season, it has a supportive sensation to help keep your feet contained, while underfoot cushioning and double Zoom Air units (1 more than the Peg 38) give you an extra pop to your step. Your trusted workhorse with wings is back. Time to fly.",
    "shoes",
    "men",
     10497,
     13900,
  ],
 [
    "Alphafly 2",
    "Men's Road Racing Shoes",
    "Once you take a few strides in the Nike Alphafly 2, you’ll never look at your favorite pair of old racing shoes the same. These rocket ships are made to help shave precious time off your personal records without surrendering the foundation you need to go the full distance. A thick, lightweight support system brings comfort and speed together so you can enjoy our greatest energy return yet while you chase your personal bests.",
    "shoes",
    "men",
     28500,
     28500,
  ],
 [
    "Pegasus Trail 4",
    "Women's Trail Running Shoes",
    "It's time to get outside. Running is your daily ritual, taking you from road to trail as you seek out new routes and goals. With a supportive, springy feel, these trail runners can take you there and back again. Underfoot traction helps keep you going over rocky terrain while still providing a smooth ride for the road. Your trusted workhorse with wings is back and ready for an off-road adventure.",
    "shoes",
    "women",
     14500,
     14500,
  ],
 [
    "Vaporfly 2",
    "Women's Road Racing Shoes",
    "Continue the next evolution of speed with a racing shoe made to you help chase new goals and records. It helps improve comfort and breathability with a redesigned upper. From a 10K to a marathon, this model, like the previous version, has the responsive cushioning and secure support to push you towards your personal best.",
    "shoes",
    "women",
     21297,
     25000,
  ],
 [
    "Structure 24",
    "Women's Road Running Shoes",
    "The Nike Structure 24 has you ready to hit the road. We tested hundreds of runners to design the crash pad under your heel that creates a cushioned, smooth transition from heel to toe. Those insights also created an airy upper with breathability right where you need it.",
    "shoes",
    "women",
     11097,
     13000,
  ],
 [
    "Zoom Fly 5",
    "Women's Road Running Shoes",
    "Bridge the gap between your weekend training run and race day in a durable design that can be deployed not just at the starting line of your favorite race, but in the days and months after your conquest. It offers comfort and reliability but with a propulsive sensation that’ll help you feel fast and fresh. That kind of versatility is uncommon in the running arena. But who said you can’t have it all?",
    "shoes",
    "women",
     13697,
     16000,
  ],
 [
    "React Infinity 3 By You",
    "Custom Women's Road Running Shoes",
    "Stay on your feet in a design that’s made to help keep you healthy while catering to your individualistic tastes in the Nike React Infinity Run 3 By You. You’re the creator with the final say, painting and picking from an extensive pallet of colors and exterior details that suite your distinctive style. Customize it to your liking and feel hopeful about endless possibilities when you hit the open road.",
    "shoes",
    "women",
     19000,
     19000,
  ],
 [
    "Dri-FIT Element",
    "Women's Running Crew",
    "The Nike Dri-FIT Element Crew returns with an updated design. An all-new sleeve features a window that lets you easily check your watch. This product is made with at least 75% recycled polyester fibers.",
    "clothes",
    "women",
     6000,
     6000,
  ],
 [
    "Nike Swoosh",
    "Women's Sports Bra",
    "With wide, comfy straps in a classic racerback design, the Nike Swoosh Sports Bra feels snug and secure while you move. Smooth, lightweight fabric wicks sweat to keep you dry, comfortable and focused. For every rep, step and jump—know that you’re supported.",
    "clothes",
    "women",
     3500,
     3500,
  ],
 [
    "Nike Sportswear",
    "Women's T-Shirt",
    "Deciding on what to wear has never been easier with this roomy tee. Whether you're wearing it alone or tucked under your favorite jacket, this soft cotton basic is sure to become an everyday favorite.",
    "clothes",
    "women",
     3000,
     3000,
  ],
 [
    "ACG Oregon Series",
    "Men's Cargo Pants",
    "Tapping into the iconic ACG Oregon Series from 2002, these cargo pants follow the original design lines for that authentic, trail-ready look and feel. They're made with durable woven fabric, and a reinforced seat to help them withstand your most rugged adventures. Multi-purpose cargo pockets give you secure space to store your hiking essentials and the integrated belt helps you find a comfy fit for the long haul.",
    "clothes",
    "men",
     20500,
     20500,
  ],
 [
    "Therma-FIT",
    "Men's Pullover Hoodie",
    "Bring the heat to your cold weather workout. In the Therma-FIT Pullover, supersoft fleece keeps the comfort levels high while you take your exercise routine to the next level. A relaxed feel means you can stretch and bench without anything holding you back.",
    "clothes",
    "men",
     6500,
     6500,
  ],
 [
    "Dri-FIT DNA",
    "Men's Basketball Shorts",
    "Take care of the future like you take care of the ball in the Nike Dri-FIT DNA Shorts. Made from at least 75% recycled polyester, they offer light, breathable fabric that's tailored for the game.",
    "clothes",
    "men",
     5000,
     5000,
  ],
 [
    "Long Sleeve Essential",
    "Men's Long-Sleeve Shirt",
    "The Nike Essential Swim Shirt offers sun protection to help guard against UV rays while you're training outdoors. Knit fabric gives this shirt natural stretch for a comfortable fit, while sweat-wicking technology helps to manage moisture.",
    "clothes",
    "men",
     4400,
     4400,
  ],
 [
    "Sportswear Windrunner",
    "Men's Hooded Jacket",
    "The Nike Sportswear Windrunner Jacket updates our first running windbreaker with lightweight fabric made from recycled materials. Design details pulled from the original version provide a heritage Nike look. This product is made with 100% recycled polyester fibers.",
    "clothes",
    "men",
     7597,
     10000,
  ],
 [
    "Nike Hat",
    "Adjustable Cap",
    "Classic and comfortable, the Nike Sportswear Heritage 86 Cap features a 6-panel design made from cotton twill fabric and an adjustable closure for a snug, secure fit.",
    "accessories",
    "unisex",
     2400,
     2400,
  ],
 [
    "Utility Speed Backpack",
    "Training Backpack (27L)",
    "The Nike Utility Speed Backpack keeps your gear close, secure and organized when commuting to and from training sessions. Cushioned straps give you comfort on the go, and the pack opens flat for easy access to must-have items.",
    "accessories",
    "men",
     7700,
     7700,
  ],
 [
    "G-Flex Belt",
    "Golf Belt",
    "The Tiger Woods Golf Belt offers a classic, clean-cut look for your day on the green. Nike Hole Reinforcer technology helps protect belt holes from wear and tear, while Nike Ultralight technology provides lightweight feel and full range of motion.",
    "accessories",
    "unisex",
     7500,
     7500,
  ],
 [
    "Essential Horizon Glasses",
    "Blue Light Glasses",
    "Sometimes it's hard to pull yourself away from the screen. The Nike Blue Light Collection features a premium lens coating that helps reduce blue light exposure for use at home, office, and gaming on your digital devices.",
    "accessories",
    "women",
     9900,
     9900,
  ],
 [
    "Maverick Polarized Glasses",
    "Golf Sunglasses",
    "A rebel on the outside, the Nike Maverick Sunglasses are pure performance on the inside. The lightweight frame features ventilation and temple arms that provide a soft, firm grip, ensuring you can wear these sunglasses for hours on the course, and off.",
    "accessories",
    "unisex",
     19900,
     19900,
  ],
 [
    "Tennis Bag",
    "Stash Duffel Bag",
    "Serena doesn't shy away from being bold and daring with her style, and neither do you. The Serena Williams Design Crew Stash Duffel is as fun as it is functional—a main compartment creates plenty of space for your gear from the court to the gym and everything else life throws your way. Need some space? The front zippered pocket provides secure small-item storage and turns inside out to store the bag easily when not in use.",
    "accessories",
    "women",
     4900,
     4900,
  ],
 [
    "Sportswear Essentials Bag",
    "Crossbody Bag",
    "The Nike Sportswear Essentials Crossbody Bag features 2 zippered pockets to let you keep the small stuff organized and easy to grab. The accessory pocket zipper pull offers quick access to smaller items, while an adjustable strap and buckle provide an easy on and off fit. This product is made with at least 50% recycled polyester fibers.",
    "accessories",
    "unisex",
     3200,
     3200,
  ],
 [
    "Invincible 3",
    "Women's Road Running Shoes",
    "With maximum cushioning to support every mile, the Invincible 3 gives you our highest level of comfort underfoot to help you stay on your feet today, tomorrow and beyond. Designed to help keep you on the run, it’s super springy and bouncy, so that you can propel down your preferred path and come back for your next run feeling ready and reinvigorated.",
    "shoes",
    "women",
     18000,
     18000,
  ],
 [
    "Vomero 16",
    "Women's Road Running Shoes",
    "The Vomero 16 adds responsive ZoomX foam cushioning, bringing an energetic pop to your stride that’s perfect for high mileage on the road. It’s super lightweight, with plenty of stretch and ventilation through the upper. Looking for the right amount of support? We’ve got you covered with an adjustable midfoot band and a stable clip at the heel.",
    "shoes",
    "women",
     16000,
     16000,
  ],
 [
    "Downshifter 12",
    "Women's Road Running Shoes",
    "Take those first steps on you running journey in the Nike Downshifter 12. It's got a supportive fit and a stable ride, with a lightweight feel that easily transitions from your workout to hanging out. This one continues our sustainability journey with a design made from at least 20% recycled content by weight. Your trek begins. Lace up and hit the road.",
    "shoes",
    "women",
     7000,
     7000,
  ],
 [
    "Renew Ride 3",
    "Women's Road Running Shoes",
    "When everyday runs are on the menu, the Nike Renew Ride 3 Premium comes through with a smooth and soft ride. It has a secure fit and cozy feel, geared for those looking to find their running potential, while a subtle wink at the tongue reminds you to find the fun on your route. It's so comfortable, you'll want to keep wearing it throughout your day.",
    "shoes",
    "women",
     5697,
     8000,
  ],
 [
    "Zoom Fly 5",
    "Men's Running Shoes",
    "Bridge the gap between your weekend training run and race day with a durable design that feels just as at home on the starting line as it does on your regular route. ZoomX foam and a carbon-fiber plate help the Nike Zoom Fly 5 offer comfort and reliability alongside a responsive propulsive sensation that’ll help you feel fast and fresh. That kind of versatility is uncommon in the running arena. But who said you can’t have it all?",
    "shoes",
    "men",
     17000,
     17000,
  ],
 [
    "Revolution 5",
    "Men's Road Running Shoes",
    "When the road beckons, answer the call in a lightweight pair that’ll keep you moving mile after mile. Soft foam cushions your stride, and a reinforced heel delivers a smooth, stable ride. Crafted with knit material for breathable support, while a minimalist design fits in just about anywhere your day takes you.",
    "shoes",
    "men ",
     4497,
     6500,
  ],
 [
    "Terra 7",
    "Men's Trail Running Shoes",
    "Run the trail in a super responsive running shoe. Fast and lightweight, it delivers a breathable and secure feel as you race over rocky paths. Updated traction lugs provide stability for your downhill miles.",
    "shoes",
    "men",
     9797,
     14000,
  ],
 [
    "Infinity React 3 Premium",
    "Men's Road Running Shoes",
    "With soft and supportive cushioning, built to help keep you on the run, the Infinity React 3 is here to help get you moving Regardless of whether your pace is snail-like or lickety-split, it helps keep you on the go. Expressive, playful graphics remind you fun can be found in every stride, even when those heavy miles won’t run themselves. So go ahead, put 1 foot in front of the other, we’ve got you.",
    "shoes",
    "men",
     17000,
     17000,
  ],
 [
    "Nike Winflo 9 Premium",
    "Men's Road Running Shoes",
    "Featuring a balanced ride to help kickstart your run, the Winflo 9 is here to help get you moving. Regardless of whether your pace is snail-like or lickety-split, this special version will help keep you on the go. Nike Air and soft, springy foam work with expressive, playful graphics to remind you fun can be found in every stride, even when those heavy miles won’t run themselves. So go ahead, put 1 foot in front of the other. We’ve got you.",
    "shoes",
    "men",
     11000,
     11000,
  ],
 [
    "React Infinity 3",
    "Men's Road Running Shoes",
    "Still 1 of our most tested shoes, the Nike React Infinity 3 has soft and supportive cushioning. Its soft, stable feel with a smooth ride will carry you through routes, long and short. A breathable upper is made to feel contained, yet flexible. We even added more cushioning around the heel and ankle for a supportive sensation. Keep running, we've got you.",
    "shoes",
    "men",
     16000,
     16000,
  ],
 [
    "Wildhorse 7",
    "Men's Trail Running Shoes",
    "Take on those tough and extreme trail runs with the rugged build of the Nike Wildhorse 7. Confidently take on rocky terrain with high-abrasion rubber on the outsole that adds durable traction. The upper delivers durable ventilation with support where you need it. Foam midsole cushioning gives a neutral feel and provides responsiveness on every mile.",
    "shoes",
    "men",
     8997,
     13000,
  ],
 [
    "React Miler 3",
    "Men's Road Running Shoes",
    "Cushioned and comfortable, just like every run should feel. The Nike React Miler 3 gives you a soft and smooth ride as your feet hit the pavement. We added stability at the heel for a secure sensation, while durable traction helps keep you going on runs long and short.",
    "shoes",
    "men",
     7197,
     12000,
  ],
 [
    "Vomero 16",
    "Men's Road Running Shoes",
    "The Vomero 16 adds responsive ZoomX foam cushioning, bringing an energetic pop to your stride that’s perfect for high mileage on the road. It’s super lightweight, with plenty of stretch and ventilation through the upper. Looking for the right amount of support? We’ve got you covered with an adjustable midfoot band and a stable clip at the heel.",
    "shoes",
    "men",
     15000,
     15000,
  ],
 [
    "Air Max 90",
    "Women's Shoes",
    "Lace up and feel the legacy. Produced at the intersection of art, music and culture, this champion running shoe helped define the ‘90s. Worn by presidents, revolutionized through collabs and celebrated through rare colorways, its striking visuals and exposed Nike Air keep it alive and well.",
    "shoes",
    "women",
     13000,
     13000,
  ],
 [
    "Air Max 270",
    "Women's Shoes",
    "Put a bounce in your step with the Nike Air Max 270. An extra-large Max Air unit wraps around the heel to cushion your every step, leaving you feeling like you’re walking on Air. The stretchy inner sleeve provides a sock-like fit for comfort that lasts. Pops of fresh colors sprinkled throughout add bright style to your day.",
    "shoes",
    "women",
     16000,
     16000,
  ],
 [
    "Repel Miler",
    "Men's Running Jacket",
    "An essential piece to your running game gets an update on the Nike Repel Miler Jacket. It's built to take on wet weather with a water-repellent design and a hood. The packable design features a look steeped in Nike's heritage. This product is made with 100% recycled polyester fibers.",
    "clothes",
    "men",
     9000,
     9000,
  ],
 [
    "Nike Sportswear",
    "Faux Fur Blanket",
    "Celebrate the seasonal shift of weather by bundling up in this blanket. Made of the coziest faux fur fleece, this statement piece does double-duty as oversized layering piece or softest spot on your couch.",
    "accessories",
    "unisex",
     17097,
     20000,
  ],
 [
    "Flex Experience Run 11 Next Nature",
    "Men's Road Running Shoes",
    "Comfortably zen, just like every run should be. With the Nike Flex Experience Run 11 Next Nature, we created a lightweight, clean design that feels as good as it looks. The shoes are supportive in all the right ways with movement so natural, you'll swear you've been wearing them for years.",
    "shoes",
    "men",
     4197,
     7000,
  ],
 [
    "Pegasus 38",
    "Men's Running Shoes",
    "Your workhorse with wings returns. The Nike Air Zoom Pegasus 38 (NFL New Orleans Saints) puts a spring in your step while showing love for your team. Breathable mesh in the upper combines the comfort and durability you want with a wider fit at the toes.",
    "shoes",
    "men",
     6500,
     13000,
  ],);

  // ==============================================

  // Variants:

  $variants = array( [
    1,
    0,
    "",
    "blue",
    "/img/products/shoes/men/Vaporfly-2-1.webp",
  ],
 [
    1,
    0,
    "",
    "green",
    "/img/products/shoes/men/Vaporfly-2-2.webp",
  ],
 [
    1,
    0,
    "",
    "white",
    "/img/products/shoes/men/Vaporfly-2-3.webp",
  ],
 [
    1,
    0,
    "",
    "grey",
    "/img/products/shoes/men/Vaporfly-2-4.jpeg",
  ],
 [
    2,
    0,
    "",
    "white",
    "/img/products/clothes/women/Dri-FIT-Slam-white.webp",
  ],
 [
    2,
    0,
    "",
    "blue",
    "/img/products/clothes/women/Dri-FIT-Slam-blue.webp",
  ],
 [
    2,
    0,
    "",
    "pink",
    "/img/products/clothes/women/Dri-FIT-Slam-pink.webp",
  ],
 [
    3,
    0,
    "",
    "purple",
    "/img/products/shoes/women/Infinity-React-3-purple.webp",
  ],
 [
    3,
    0,
    "",
    "pink",
    "/img/products/shoes/women/Infinity-React-3-pink.webp",
  ],
 [
    3,
    0,
    "",
    "grey",
    "/img/products/shoes/women/Infinity-React-3-grey.webp",
  ],
 [
    3,
    0,
    "",
    "white",
    "/img/products/shoes/women/Infinity-React-3-white.webp",
  ],
 [
    4,
    0,
    "",
    "blue",
    "/img/products/clothes/women/Dri-FIT-One-blue.webp",
  ],
 [
    4,
    0,
    "",
    "pink",
    "/img/products/clothes/women/Dri-FIT-One-pink.webp",
  ],
 [
    5,
    0,
    "",
    "green",
    "/img/products/shoes/men/Air-Zoom-Rival-Fly-3-green.webp",
  ],
 [
    5,
    0,
    "",
    "blue",
    "/img/products/shoes/men/Air-Zoom-Rival-Fly-3-blue.webp",
  ],
 [
    5,
    0,
    "",
    "black",
    "/img/products/shoes/men/Air-Zoom-Rival-Fly-3-black.webp",
  ],
 [
    6,
    0,
    "",
    "brown",
    "/img/products/clothes/women/Sportswear-Phoenix-Fleece-brown.webp",
  ],
 [
    6,
    0,
    "",
    "red",
    "/img/products/clothes/women/Sportswear-Phoenix-Fleece-red.webp",
  ],
 [
    7,
    0,
    "",
    "orange",
    "/img/products/shoes/men/invincible-2-orange.webp",
  ],
 [
    7,
    0,
    "",
    "grey",
    "/img/products/shoes/men/invincible-2-grey.webp",
  ],
 [
    7,
    0,
    "",
    "pink",
    "/img/products/shoes/men/invincible-2-pink.webp",
  ],
 [
    7,
    0,
    "",
    "black",
    "/img/products/shoes/men/invincible-2-black.webp",
  ],
 [
    8,
    0,
    "",
    "blue",
    "/img/products/shoes/men/Zegama-1.webp",
  ],
 [
    8,
    0,
    "",
    "green",
    "/img/products/shoes/men/Zegama-2.webp",
  ],
 [
    9,
    0,
    "",
    "white",
    "/img/products/shoes/men/pegasus-39-white.webp",
  ],
 [
    9,
    0,
    "",
    "green",
    "/img/products/shoes/men/pegasus-39-green.webp",
  ],
 [
    9,
    0,
    "",
    "pink",
    "/img/products/shoes/men/pegasus-39-pink.webp",
  ],
 [
    9,
    0,
    "",
    "purple",
    "/img/products/shoes/men/pegasus-39-purple.webp",
  ],
 [
    10,
    0,
    "",
    "green",
    "/img/products/shoes/men/alphafly-2-green.webp",
  ],
 [
    10,
    0,
    "",
    "orange",
    "/img/products/shoes/men/alphafly-2-orange.webp",
  ],
 [
    11,
    0,
    "",
    "pink",
    "/img/products/shoes/women/Pegasus-Trail-4-pink.webp",
  ],
 [
    11,
    0,
    "",
    "purple",
    "/img/products/shoes/women/Pegasus-Trail-4-purple.webp",
  ],
 [
    11,
    0,
    "",
    "red",
    "/img/products/shoes/women/Pegasus-Trail-4-red.webp",
  ],
 [
    11,
    0,
    "",
    "brown",
    "/img/products/shoes/women/Pegasus-Trail-4-brown.webp",
  ],
 [
    12,
    0,
    "",
    "orange",
    "/img/products/shoes/women/vaporfly-2-1.avif",
  ],
 [
    12,
    0,
    "",
    "black",
    "/img/products/shoes/women/vaporfly-2-2.jpeg",
  ],
 [
    12,
    0,
    "",
    "pink",
    "/img/products/shoes/women/vaporfly-2-3.jpeg",
  ],
 [
    12,
    0,
    "",
    "yellow",
    "/img/products/shoes/women/vaporfly-2-4.jpeg",
  ],
 [
    13,
    0,
    "",
    "white",
    "/img/products/shoes/women/Structure-24-white.webp",
  ],
 [
    13,
    0,
    "",
    "pink",
    "/img/products/shoes/women/Structure-24-pink.webp",
  ],
 [
    13,
    0,
    "",
    "pink",
    "/img/products/shoes/women/Structure-24-pink-2.webp",
  ],
 [
    13,
    0,
    "",
    "black",
    "/img/products/shoes/women/Structure-24-black.webp",
  ],
 [
    14,
    0,
    "",
    "purple",
    "/img/products/shoes/women/Zoom-Fly-5-purple.webp",
  ],
 [
    14,
    0,
    "",
    "green",
    "/img/products/shoes/women/Zoom-Fly-5-green.webp",
  ],
 [
    14,
    0,
    "",
    "pink",
    "/img/products/shoes/women/Zoom-Fly-5-pink.webp",
  ],
 [
    14,
    0,
    "",
    "black",
    "/img/products/shoes/women/Zoom-Fly-5-black.jpeg",
  ],
 [
    15,
    0,
    "",
    "white",
    "/img/products/shoes/women/React-Infinity-3 By-You-white.jpeg",
  ],
 [
    15,
    0,
    "",
    "pink",
    "/img/products/shoes/women/React-Infinity-3 By-You-pink.webp",
  ],
 [
    15,
    0,
    "",
    "red",
    "/img/products/shoes/women/React-Infinity-3 By-You-red.webp",
  ],
 [
    15,
    0,
    "",
    "black",
    "/img/products/shoes/women/React-Infinity-3 By-You-black.webp",
  ],
 [
    16,
    0,
    "",
    "yellow",
    "/img/products/clothes/women/Dri-FIT-Element-yellow.webp",
  ],
 [
    16,
    0,
    "",
    "grey",
    "/img/products/clothes/women/Dri-FIT-Element-grey.jpeg",
  ],
 [
    16,
    0,
    "",
    "black",
    "/img/products/clothes/women/Dri-FIT-Element-black.webp",
  ],
 [
    16,
    0,
    "",
    "black",
    "/img/products/clothes/women/Dri-FIT-Element-black-2.webp",
  ],
 [
    17,
    0,
    "",
    "yellow",
    "/img/products/clothes/women/Nike-Swoosh-yellow.webp",
  ],
 [
    17,
    0,
    "",
    "green",
    "/img/products/clothes/women/Nike-Swoosh-green.webp",
  ],
 [
    17,
    0,
    "",
    "pink",
    "/img/products/clothes/women/Nike-Swoosh-pink.webp",
  ],
 [
    18,
    0,
    "",
    "pink",
    "/img/products/clothes/women/Nike-Sportswear-pink.webp",
  ],
 [
    18,
    0,
    "",
    "white",
    "/img/products/clothes/women/Nike-Sportswear-white.webp",
  ],
 [
    19,
    0,
    "",
    "green",
    "/img/products/clothes/men/cargo-pants-green.webp",
  ],
 [
    20,
    0,
    "",
    "purple",
    "/img/products/clothes/men/themal-fit-hoodie-purple.webp",
  ],
 [
    20,
    0,
    "",
    "red",
    "/img/products/clothes/men/themal-fit-hoodie-red.webp",
  ],
 [
    20,
    0,
    "",
    "blue",
    "/img/products/clothes/men/themal-fit-hoodie-blue.webp",
  ],
 [
    20,
    0,
    "",
    "grey",
    "/img/products/clothes/men/themal-fit-hoodie-grey.jpeg",
  ],
 [
    21,
    0,
    "",
    "blue",
    "/img/products/clothes/men/Dri-FIT-DNA-shorts-blue.webp",
  ],
 [
    21,
    0,
    "",
    "grey",
    "/img/products/clothes/men/Dri-FIT-DNA-shorts-grey.webp",
  ],
 [
    21,
    0,
    "",
    "red",
    "/img/products/clothes/men/Dri-FIT-DNA-shorts-red.webp",
  ],
 [
    22,
    0,
    "",
    "grey",
    "/img/products/clothes/men/long-sleeve-essential-grey.webp",
  ],
 [
    22,
    0,
    "",
    "white",
    "/img/products/clothes/men/long-sleeve-essential-white.webp",
  ],
 [
    22,
    0,
    "",
    "black",
    "/img/products/clothes/men/long-sleeve-essential-black.webp",
  ],
 [
    23,
    0,
    "",
    "green",
    "/img/products/clothes/men/Sportswear-Windrunner-green.webp",
  ],
 [
    23,
    0,
    "",
    "black",
    "/img/products/clothes/men/Sportswear-Windrunner-black.webp",
  ],
 [
    23,
    0,
    "",
    "blue",
    "/img/products/clothes/men/Sportswear-Windrunner-blue.webp",
  ],
 [
    23,
    0,
    "",
    "red",
    "/img/products/clothes/men/Sportswear-Windrunner-red.webp",
  ],
 [
    24,
    0,
    "",
    "blue",
    "/img/products/accessories/unisex/nike-hat-blue.webp",
  ],
 [
    24,
    0,
    "",
    "black",
    "/img/products/accessories/unisex/nike-hat-black.webp",
  ],
 [
    24,
    0,
    "",
    "brown",
    "/img/products/accessories/unisex/nike-hat-brown.webp",
  ],
 [
    24,
    0,
    "",
    "white",
    "/img/products/accessories/unisex/nike-hat-white.webp",
  ],
 [
    25,
    0,
    "",
    "black",
    "/img/products/accessories/men/backpack.webp",
  ],
 [
    26,
    0,
    "",
    "black",
    "/img/products/accessories/unisex/belt-g-flex-black.webp",
  ],
 [
    26,
    0,
    "",
    "white",
    "/img/products/accessories/unisex/belt-g-flex-white.webp",
  ],
 [
    27,
    0,
    "",
    "pink",
    "/img/products/accessories/women/Essential-Horizon-pink.webp",
  ],
 [
    27,
    0,
    "",
    "white",
    "/img/products/accessories/women/Essential-Horizon-white.webp",
  ],
 [
    27,
    0,
    "",
    "black",
    "/img/products/accessories/women/Essential-Horizon-black.webp",
  ],
 [
    28,
    0,
    "",
    "blue",
    "/img/products/accessories/unisex/Maverick-Polarized-Glasses-blue.webp",
  ],
 [
    28,
    0,
    "",
    "red",
    "/img/products/accessories/unisex/Maverick-Polarized-Glasses-red.webp",
  ],
 [
    28,
    0,
    "",
    "black",
    "/img/products/accessories/unisex/Maverick-Polarized-Glasses-black.webp",
  ],
 [
    29,
    0,
    "",
    "white",
    "/img/products/accessories/unisex/tennis-bag-white.jpeg",
  ],
 [
    30,
    0,
    "",
    "black",
    "/img/products/accessories/unisex/Sportswear-Essentials-Bag-black.webp",
  ],
 [
    30,
    0,
    "",
    "blue",
    "/img/products/accessories/unisex/Sportswear-Essentials-Bag-blue.webp",
  ],
 [
    30,
    0,
    "",
    "white",
    "/img/products/accessories/unisex/Sportswear-Essentials-Bag-white.webp",
  ],
 [
    31,
    0,
    "",
    "pink",
    "/img/products/shoes/women/Invincible-3-pink.webp",
  ],
 [
    31,
    0,
    "",
    "grey",
    "/img/products/shoes/women/Invincible-3-grey.webp",
  ],
 [
    31,
    0,
    "",
    "black",
    "/img/products/shoes/women/Invincible-3-black.webp",
  ],
 [
    31,
    0,
    "",
    "black",
    "/img/products/shoes/women/Invincible-3-black-2.webp",
  ],
 [
    32,
    0,
    "",
    "pink",
    "/img/products/shoes/women/Vomero-16-pink.webp",
  ],
 [
    32,
    0,
    "",
    "black",
    "/img/products/shoes/women/Vomero-16-black.webp",
  ],
 [
    33,
    0,
    "",
    "pink",
    "/img/products/shoes/women/Downshifter-12-pink.webp",
  ],
 [
    33,
    0,
    "",
    "white",
    "/img/products/shoes/women/Downshifter-12-grey.webp",
  ],
 [
    34,
    0,
    "",
    "white",
    "/img/products/shoes/women/Renew-Ride-3-white.webp",
  ],
 [
    34,
    0,
    "",
    "pink",
    "/img/products/shoes/women/Renew-Ride-3-pink.webp",
  ],
 [
    34,
    0,
    "",
    "green",
    "/img/products/shoes/women/Renew-Ride-3-green.webp",
  ],
 [
    35,
    0,
    "",
    "green",
    "/img/products/shoes/men/Zoom-Fly-5-green.webp",
  ],
 [
    35,
    0,
    "",
    "black",
    "/img/products/shoes/men/Zoom-Fly-5-black.webp",
  ],
 [
    36,
    0,
    "",
    "grey",
    "/img/products/shoes/men/Nike-Revolution-5-grey.webp",
  ],
 [
    37,
    0,
    "",
    "orange",
    "/img/products/shoes/men/Terra-7-orange.webp",
  ],
 [
    38,
    0,
    "",
    "brown",
    "/img/products/shoes/men/Infinity-React-3-Premium.webp",
  ],
 [
    39,
    0,
    "",
    "white",
    "/img/products/shoes/men/Nike-Winflo-9-Premium.webp",
  ],
 [
    40,
    0,
    "",
    "brown",
    "/img/products/shoes/men/React-Infinity-3-brown.webp",
  ],
 [
    40,
    0,
    "",
    "grey",
    "/img/products/shoes/men/React-Infinity-3-grey.webp",
  ],
 [
    40,
    0,
    "",
    "black",
    "/img/products/shoes/men/React-Infinity-3-black.webp",
  ],
 [
    41,
    0,
    "",
    "grey",
    "/img/products/shoes/men/Wildhorse-7-grey.webp",
  ],
 [
    41,
    0,
    "",
    "black",
    "/img/products/shoes/men/Wildhorse-7-black.webp",
  ],
 [
    42,
    0,
    "",
    "green",
    "/img/products/shoes/men/React-Miler-3-green.webp",
  ],
 [
    42,
    0,
    "",
    "black",
    "/img/products/shoes/men/React-Miler-3-black.webp",
  ],
 [
    43,
    0,
    "",
    "grey",
    "/img/products/shoes/men/Vomero-16-grey.webp",
  ],
 [
    43,
    0,
    "",
    "blue",
    "/img/products/shoes/men/Vomero-16-blue.webp",
  ],
 [
    44,
    0,
    "",
    "white",
    "/img/products/shoes/women/Air-Max-90-white.webp",
  ],
 [
    44,
    0,
    "",
    "pink",
    "/img/products/shoes/women/Air-Max-90-pink.webp",
  ],
 [
    45,
    0,
    "",
    "white",
    "/img/products/shoes/women/Nike-Air-Max-270-white.webp",
  ],
 [
    45,
    0,
    "",
    "white",
    "/img/products/shoes/women/Nike-Air-Max-270-white-2.webp",
  ],
 [
    45,
    0,
    "",
    "white",
    "/img/products/shoes/women/Nike-Air-Max-270-white-3.webp",
  ],
 [
    45,
    0,
    "",
    "purple",
    "/img/products/shoes/women/Nike-Air-Max-270-purple.webp",
  ],
 [
    46,
    0,
    "",
    "green",
    "/img/products/clothes/men/Repel-Miler-1.webp",
  ],
 [
    46,
    0,
    "",
    "black",
    "/img/products/clothes/men/Repel-Miler-2.webp",
  ],
 [
    46,
    0,
    "",
    "grey",
    "/img/products/clothes/men/Repel-Miler-3.webp",
  ],
 [
    47,
    0,
    "",
    "white",
    "/img/products/accessories/unisex/Faux-Fur-Blanket-1.webp",
  ],
 [
    47,
    0,
    "",
    "brown",
    "/img/products/accessories/unisex/Faux-Fur-Blanket-2.webp",
  ],
 [
    47,
    0,
    "",
    "black",
    "/img/products/accessories/unisex/Faux-Fur-Blanket-3.webp",
  ],
 [
    48,
    0,
    "",
    "grey",
    "/img/products/shoes/men/Flex-Experience-Run-11-grey-1.webp",
  ],
 [
    48,
    0,
    "",
    "grey",
    "/img/products/shoes/men/Flex-Experience-Run-11-grey-2.webp",
  ],
 [
    48,
    0,
    "",
    "black",
    "/img/products/shoes/men/Flex-Experience-Run-11-black.webp",
  ],
 [
    48,
    0,
    "",
    "blue",
    "/img/products/shoes/men/Flex-Experience-Run-11-blue.webp",
  ],
 [
    49,
    0,
    "",
    "grey",
    "/img/products/shoes/men/Pegasus-38-3.webp",
  ],
 [
    49,
    0,
    "",
    "red",
    "/img/products/shoes/men/Pegasus-38-2.webp",
  ],
 [
    49,
    0,
    "",
    "grey",
    "/img/products/shoes/men/Pegasus-38-1.webp",
  ],
 [
    49,
    0,
    "",
    "black",
    "/img/products/shoes/men/Pegasus-38-4.webp",
  ],);

  // ==============================================


